

% Definir las peliculas recomendadas con su sinopsis
pelicula_recomendada(feliz, accion, 'Rapidos y Furiosos 9', 'Rapidos y Furiosos 9 es una pelicula de accion y ciencia ficcion del 2021 con una duracion de 142 minutos. La trama sigue a Dominic Toretto y su equipo mientras se enfrentan a un enemigo peligroso y poderoso.').
pelicula_recomendada(feliz, fantasia, 'Harry Potter y la Piedra Filosofal', 'Harry Potter y la Piedra Filosofal es una pelicula de aventuras y fantasia dirigida por Chris Columbus y basada en la novela de J.K. Rowling. La pelicula tiene una duracion de aproximadamente 2 horas y sigue la historia de un joven huerfano, Harry Potter, quien descubre que es un mago y es admitido en la escuela de magia Hogwarts. Alli, junto a sus amigos, descubre la existencia de la piedra filosofal y se enfrenta al malvado Lord Voldemort mientras desentraña los misterios de su propio pasado.').
pelicula_recomendada(feliz, amor, 'Cartas a Julieta', 'Cartas a Julieta es una pelicula romantica dirigida por Gary Winick con una duracion de aproximadamente 1 hora y 45 minutos. La historia sigue a una joven llamada Sophie que viaja a Verona, Italia, donde encuentra una carta de amor perdida y se embarca en una busqueda para reunir a sus autores. A lo largo de su viaje, Sophie descubre el poder del amor y la importancia de seguir el corazon en cuestiones del amor verdadero.').
pelicula_recomendada(feliz, comedia, 'Shrek I', 'Shrek es una pelicula de animacion y comedia dirigida por Andrew Adamson y Vicky Jenson, con una duracion de aproximadamente 1 hora y 30 minutos. La pelicula cuenta la historia de Shrek, un ogro solitario que se embarca en una mision para rescatar a la princesa Fiona de un dragon y devolverla a su torre, encomendada por el malvado Lord Farquaad. A lo largo de su aventura, Shrek descubre el valor de la amistad y el amor verdadero mientras lucha contra estereotipos y prejuicios en el reino de Duloc.').
pelicula_recomendada(feliz, triste, 'Titanic', 'Titanic es una pelicula epica de romance y drama dirigida por James Cameron con una duracion de aproximadamente 3 horas y 15 minutos. La pelicula narra la historia de Jack y Rose, dos pasajeros a bordo del Titanic, un lujoso transatlantico que choca con un iceberg y se hunde. La pelicula es conocida por su historia de amor tragica que se desarrolla en el contexto del desastre del Titanic.').

pelicula_recomendada(triste, accion, 'Gladiador', 'Gladiador es una pelicula de epica y accion dirigida por Ridley Scott con una duracion de aproximadamente 2 horas y 35 minutos. La pelicula sigue la historia del general romano Maximo, quien es traicionado y condenado a la esclavitud despues del asesinato de su familia. Maximo se convierte en un gladiador y busca venganza contra el corrupto emperador Comodo, desafiando el poderoso Imperio Romano. A lo largo de la pelicula, Maximo lucha por su libertad y la justicia en un emocionante relato de venganza y redencion en la antigua Roma.').
pelicula_recomendada(triste, fantasia, 'Up: una aventura de altura', 'Up es una pelicula de animacion de Pixar dirigida por Pete Docter y Bob Peterson, con una duracion de aproximadamente 1 hora y 36 minutos. La pelicula narra la historia de Carl Fredricksen, un anciano viudo que decide cumplir el sueno de su difunta esposa de viajar a Sudamerica. Utiliza miles de globos para elevar su casa y embarcarse en una aventura inesperada. Durante su viaje, se encuentra con Russell, un nino explorador, y juntos enfrentan desafios y descubren el valor de la amistad y el amor en un emocionante viaje de autodescubrimiento.').
pelicula_recomendada(triste, amor, 'Orgullo y Prejuicio', 'Orgullo y Prejuicio es una pelicula de epoca y romance dirigida por Joe Wright, con una duracion de aproximadamente 2 horas y 9 minutos. Basada en la novela de Jane Austen, la pelicula sigue la vida de Elizabeth Bennet, una joven inteligente y obstinada, y su relacion con el orgulloso y apuesto Sr. Darcy. A medida que se desarrolla la trama, los personajes luchan con sus prejuicios y orgullo, y eventualmente encuentran el amor y la comprension mutua en un contexto social riguroso del siglo XIX en Inglaterra.').
pelicula_recomendada(triste, comedia, 'Un espia y medio', 'Un Espia y Medio es una pelicula de accion y comedia dirigida por Rawson Marshall Thurber, con una duracion de aproximadamente 1 hora y 47 minutos. La pelicula sigue a Calvin Joyner, un hombre promedio que fue el chico mas popular de la escuela secundaria. Se reune con un antiguo companero de clase, Bob Stone, quien resulta ser un espia de la CIA. Juntos, se embarcan en una aventura llena de accion y humor mientras intentan desentranar una conspiracion y salvar el mundo. La pelicula combina elementos de comedia y accion en una historia de amistad inusual.').
pelicula_recomendada(triste, triste, 'El Laberinto del Fauno', 'El Laberinto del Fauno es una pelicula de fantasia dirigida por Guillermo del Toro con una duracion de aproximadamente 1 hora y 58 minutos. La pelicula se desarrolla en la posguerra espanola y sigue la historia de Ofelia, una nina que descubre un mundo magico subterraneo habitado por criaturas fantasticas. A medida que escapa de la brutalidad del mundo real, Ofelia se embarca en una aventura oscura y misteriosa.').

pelicula_recomendada(enojado, accion, 'Busqueda implacable', 'Busqueda Implacable I es una pelicula de accion dirigida por Pierre Morel con una duracion de aproximadamente 1 hora y 33 minutos. La pelicula sigue la historia de Bryan Mills, un exagente de la CIA, quien debe utilizar sus habilidades especiales para rescatar a su hija Kim, quien ha sido secuestrada por un grupo de traficantes de personas en Paris. Bryan se embarca en una busqueda implacable para encontrar a su hija y enfrenta numerosos obstaculos mientras lucha contra el tiempo para salvarla. La pelicula es una intensa historia de rescate y venganza llena de accion.').
pelicula_recomendada(enojado, fantasia, 'Jurassic Park', 'Jurassic Park es una pelicula de ciencia ficcion y aventuras dirigida por Steven Spielberg, con una duracion de aproximadamente 2 horas y 7 minutos. La pelicula sigue la historia de un grupo de cientificos y aventureros que visitan un parque tematico de dinosaurios geneticamente recreados en una isla remota. Cuando el sistema de seguridad del parque falla, los dinosaurios escapan y amenazan la vida de los visitantes. La película es una emocionante aventura que explora los peligros de jugar con la naturaleza y la tecnologia, mientras presenta impresionantes efectos visuales que dan vida a los dinosaurios prehistoricos.').
pelicula_recomendada(enojado, amor, 'The Notebook', 'The Notebook es una pelicula de romance dirigida por Nick Cassavetes con una duracion de aproximadamente 2 horas. La pelicula cuenta la historia de Noah y Allie, dos jovenes que se enamoran profundamente durante el verano de 1940, pero son separados debido a las diferencias sociales y la Segunda Guerra Mundial. A lo largo de los anos, sus vidas toman diferentes caminos, pero su amor perdura a traves de las decadas. La pelicula explora temas de amor, pasion y el poder de la memoria en una emotiva historia que atraviesa el tiempo.').
pelicula_recomendada(enojado, comedia, 'Una esposa de mentira', 'Una Esposa de Mentira es una película de comedia dirigida por Dennis Dugan con una duracion de aproximadamente 1 hora y 57 minutos. La trama gira en torno a Danny, un cirujano plastico interpretado por Adam Sandler, que finge estar casado para seducir a mujeres, pero su vida da un giro inesperado cuando conoce a Palmer, una mujer que cree que esta divorciado. Danny le pide a su asistente Katherine, interpretada por Jennifer Aniston, que se haga pasar por su esposa. La pelicula se desarrolla con una serie de situaciones comicas y romanticas mientras Danny intenta mantener su engaño.').
pelicula_recomendada(enojado, triste, 'The Dark Knight', 'The Dark Knight es una pelicula de superheroes y accion dirigida por Christopher Nolan con una duracion de aproximadamente 2 horas y 32 minutos. La pelicula sigue la historia del Caballero de la Noche, Batman, mientras se enfrenta al Joker, un villano caotico que amenaza a Gotham City. La pelicula es conocida por su atmosfera sombria y la actuacion iconica de Heath Ledger como el Joker.').

% Predicado para obtener la película recomendada y su sinopsis
obtener_pelicula_recomendada(Animo, Genero, PeliculaRecomendada, Sinopsis) :-
    findall((Pelicula, SinopsisPelicula), (pelicula_recomendada(Animo, Genero, Pelicula, SinopsisPelicula)), Peliculas),
    random_member((PeliculaRecomendada, Sinopsis), Peliculas).

